# Generated by Django 5.2.3 on 2025-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=125)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, null=True)),
                ('funcao_responsavel', models.CharField(blank=True, choices=[('Médico', 'Médico'), ('Enfermeiro', 'Enfermeiro'), ('Técnico de Enfermagem', 'Técnico de Enfermagem'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Nutricionista', 'Nutricionista'), ('Farmacêutico', 'Farmacêutico'), ('Psicólogo', 'Psicólogo'), ('Assistente Social', 'Assistente Social'), ('Técnico de Radiologia', 'Técnico de Radiologia'), ('Técnico de Laboratório', 'Técnico de Laboratório'), ('Coordenador', 'Coordenador'), ('Supervisor', 'Supervisor'), ('Auxiliar Administrativo', 'Auxiliar Administrativo')], max_length=125, null=True)),
                ('serial', models.CharField(blank=True, max_length=14, null=True)),
                ('data_solicitacao', models.DateField(blank=True, default=None, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_modificacao', models.DateField(auto_now=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criador', models.CharField(blank=True, max_length=125, null=True)),
                ('modificador', models.CharField(blank=True, max_length=125, null=True)),
                ('token_entregue', models.BooleanField(default=False)),
                ('token_ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
