# Generated by Django 5.2 on 2025-06-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=125)),
                ('cpf_responsavel', models.CharField(max_length=11)),
                ('funcao_responsavel', models.CharField(max_length=125)),
                ('setor_responsavel', models.CharField(max_length=125)),
                ('telefone_responsavel', models.CharField(max_length=15)),
                ('serial', models.CharField(max_length=14)),
                ('data_solicitacao', models.DateField()),
                ('data_entrega', models.DateField()),
                ('data_modificacao', models.DateField(auto_now=True)),
                ('data_exclusao', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
