# Generated by Django 5.2 on 2025-06-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='data_exclusao',
        ),
    ]
